### ISSUE TITLE
HABTM relationships

### ISSUE THREAD

**Issue by HenryHaller** [gregschmit/rails-rest-framework#32]
I was looking into what it would take for an external API client to instrument PMS Guest <> Room relationships and was struggling so I looked into the RRF source and I think this change might address the issue:

![image](https://github.com/gregschmit/rails-rest-framework/assets/1879155/4d8811aa-5556-4455-a956-3f04c5762078)

I can always do a "1-off" in the specific controller to make the specific field accessible, but I was wondering if there had ever been consideration of making all HABTM relationships addressable like this?

So far I've only tested this inside a 1-off scenario like this, and it seems to work as intended:

![image](https://github.com/gregschmit/rails-rest-framework/assets/1879155/c41aaaca-cf24-4b37-a787-10d1d8ca22cb)

**Comment by gregschmit** [comment]
HABTM are already included, unless they are excluded by `large_reverse_association_tables`.
